# Generated by Django 3.1.4 on 2020-12-05 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_before', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('paid_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installments', models.ManyToManyField(related_name='installment_payment_plan', to='payments.Installment')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_plans', to='orders.order')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('converted_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('converted_amount', models.FloatField()),
                ('from_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sent_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payments', to='orders.order')),
                ('payment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_payments', to='payments.paymentplan')),
                ('to_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
