# Generated by Django 3.1.4 on 2020-12-13 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20201213_2156'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('pay_before', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('paid_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericInstallmentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('payment_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('converted_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('converted_amount', models.FloatField()),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_generic_installment_payments', to=settings.AUTH_USER_MODEL)),
                ('generic_installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_payment', to='payments.genericinstallment')),
                ('to_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_generic_installment_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('payment_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('converted_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('converted_amount', models.FloatField()),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_generic_payments', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_generic_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('pay_before', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('paid_at', models.DateTimeField(default=None, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInstallmentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('payment_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('converted_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('converted_amount', models.FloatField()),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_order_installment_payments', to=settings.AUTH_USER_MODEL)),
                ('order_installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_payment', to='payments.orderinstallment')),
                ('to_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_order_installment_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_field_values', models.JSONField(db_index=True)),
                ('payment_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('converted_currency', models.CharField(max_length=10)),
                ('conversion_rate', models.FloatField(default=1.0)),
                ('converted_amount', models.FloatField()),
                ('from_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_order_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payment', to='orders.order')),
                ('to_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_order_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='to_person',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='installments',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='payer',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
