# Generated by Django 3.1.4 on 2020-12-14 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20201214_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericinstallment',
            name='payer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generic_installments', to=settings.AUTH_USER_MODEL),
        ),
    ]
