# Generated by Django 3.1.4 on 2020-12-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_genericinstallment_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericinstallment',
            name='remind_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='orderinstallment',
            name='remind_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
