# Generated by Django 3.1.4 on 2020-12-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201221_0155'),
        ('payments', '0007_auto_20201217_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
    ]
