# Generated by Django 3.1.4 on 2020-12-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20201222_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='installment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.installment'),
        ),
    ]
