# Generated by Django 3.1.4 on 2020-12-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20201210_1015'),
        ('users', '0003_auto_20201206_1016'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_currency',
            new_name='selling_price_currency',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_per_unit',
            new_name='selling_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_of_order_item', to='orders.OrderItem'),
        ),
        migrations.CreateModel(
            name='InventoryOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('inventory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_item_orders', to='inventories.inventoryitem')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.orderitem')),
                ('supplier_price_per_unit', models.FloatField(null=True)),
                ('supplier_price_currency', models.CharField(max_length=10, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_supplier_orders', to='users.supplier')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.orderitem',),
        ),
    ]
