# Generated by Django 3.1.4 on 2020-12-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201220_2220'),
        ('products', '0005_auto_20201212_0024'),
        ('orders', '0007_auto_20201221_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorderitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='users.supplier'),
        ),
    ]
