# Generated by Django 3.1.4 on 2020-12-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_inventoryitem_supplier'),
        ('orders', '0009_auto_20201221_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='inventory_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventories.inventoryitem'),
        ),
    ]
