# Generated by Django 3.1.4 on 2020-12-05 20:26

from django.db import migrations, models
import users.models
import generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
        migrations.AddField(
            model_name='supplier',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
    ]
