# Generated by Django 3.1.4 on 2020-12-06 07:16

from django.db import migrations, models
import generics.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201205_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ui_language',
            field=models.CharField(choices=[('tr-tr', 'tr-tr'), ('en-us', 'en-us')], default='tr-tr', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='ui_language',
            field=models.CharField(choices=[('tr-tr', 'tr-tr'), ('en-us', 'en-us')], default='tr-tr', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ui_language',
            field=models.CharField(choices=[('tr-tr', 'tr-tr'), ('en-us', 'en-us')], default='tr-tr', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=generics.models.get_profile_image_path),
        ),
    ]
