# Generated by Django 3.1.4 on 2020-12-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201212_0024'),
        ('users', '0003_auto_20201206_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='suppliers', to='products.Product'),
        ),
    ]
