# Generated by Django 3.1.4 on 2020-12-05 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFieldAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type_name', models.CharField(choices=[('bool', 'bool'), ('int', 'int'), ('float', 'float'), ('str', 'str'), ('datetime', 'datetime'), ('choice', 'choice')], default='str', max_length=20)),
                ('max_length', models.IntegerField(default=100)),
                ('default', models.CharField(default=None, max_length=100, null=True)),
                ('show_in_summary', models.BooleanField(default=False)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=30)),
            ],
        ),
    ]
