# Generated by Django 3.1.4 on 2020-12-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0002_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldattributes',
            name='field_name',
            field=models.CharField(default='key', max_length=50),
        ),
    ]
