# Generated by Django 3.1.4 on 2020-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0005_auto_20201206_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldattributes',
            name='type_name',
            field=models.CharField(choices=[('bool', 'bool'), ('int', 'int'), ('float', 'float'), ('str', 'str'), ('datetime', 'datetime'), ('choices', 'choices')], default='str', max_length=20),
        ),
    ]
