# Generated by Django 3.1.4 on 2020-12-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0009_auto_20201207_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldattributes',
            name='type_name',
            field=models.CharField(choices=[('bool', 'bool'), ('int', 'int'), ('float', 'float'), ('str', 'str'), ('datetime', 'datetime'), ('choices', 'choices'), ('image', 'image')], default='str', max_length=20),
        ),
    ]
