# Generated by Django 3.1.4 on 2020-12-10 19:53

from django.db import migrations, models
import generics.helper


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0010_auto_20201210_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to=generics.helper.get_generic_image_path)),
            ],
        ),
    ]
