# Generated by Django 3.1.4 on 2020-12-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0011_genericimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericimagemodel',
            name='field_name',
            field=models.CharField(default='key', max_length=8),
        ),
        migrations.AddField(
            model_name='genericimagemodel',
            name='model_name',
            field=models.CharField(default='model', max_length=100),
        ),
        migrations.AddField(
            model_name='genericimagemodel',
            name='obj_id',
            field=models.IntegerField(default=0),
        ),
    ]
