# Generated by Django 3.1.4 on 2020-12-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0012_auto_20201211_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericImageModel',
            new_name='GenericImage',
        ),
    ]
