# Generated by Django 3.1.4 on 2020-12-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0013_auto_20201212_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.CharField(max_length=250),
        ),
    ]
