# Generated by Django 3.1.4 on 2020-12-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='currency',
            new_name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price_per_unit',
        ),
    ]
