# Generated by Django 3.1.4 on 2020-12-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20201210_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='default_inventory', max_length=100),
        ),
    ]
