# Generated by Django 3.1.4 on 2020-12-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201206_1016'),
        ('inventories', '0004_auto_20201212_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_in_inventory', to='users.supplier'),
        ),
    ]
